In [1]:
import cityflow

eng = cityflow.Engine("config.json", thread_num=1)


In [2]:
x = 0
while x < 100:
 eng.next_step()
 x+=1

In [3]:
import numpy as np
state = np.array(np.zeros((8))) 
state[0]
print(state)

ValueError: setting an array element with a sequence.

In [1]:
import numpy as np
x = np.array(np.zeros((8,3)))
print(x[0])
x[0] = np.array([1,2,3])
print(x)


[0. 0. 0.]
[[1. 2. 3.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
eng.get_lane_waiting_vehicle_count()["et_0"]
eng.get_lane_vehicle_count()["et_0"]

20

In [4]:
import numpy as np
x = np.array([[100,100],[100,100],[100,100],[100,100],[100,100],[100,100],[100,100],[100,100]])
print(x)
x[0] = np.array([50,60])
print(x)

state = np.array(np.zeros((8,2))) 
state

[[100 100]
 [100 100]
 [100 100]
 [100 100]
 [100 100]
 [100 100]
 [100 100]
 [100 100]]
[[ 50  60]
 [100 100]
 [100 100]
 [100 100]
 [100 100]
 [100 100]
 [100 100]
 [100 100]]


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])